### ISSUE TITLE
If any applications not found, given appropriate error

### ISSUE THREAD

**Issue by loudbinary** [webteks/backendless_schema_tools#1]
Since we first login as develop, and then gather a list of applications via that endpoint and then we start gather information for any application provided on the command line we could then simple do a quick compare - See if we found apps, and if not give a friendly error message instance of this innocuous error message 

> TypeError: Cannot read property 'id' of undefined
>     at Backendless.getAppVersions (/home/loudbinary/.nvm/versions/node/v6.9.4/lib/node_modules/@webteks/backendless_schema_tools/libs/backendless-console-api.js:92:38)
>     at login.then.then.then (/home/loudbinary/.nvm/versions/node/v6.9.4/lib/node_modules/@webteks/backendless_schema_tools/libs/backendless-console-api.js:184:30)
>     at process._tickCallback (internal/process/next_tick.js:103:7)
> TypeError: Cannot read property 'id' of undefined

**Comment by realjvernon** [comment]
This is no longer relevant to BE4
